# Generated by Django 3.2.25 on 2025-03-16 12:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copropriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=50)),
                ('comptable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptable_pour', to=settings.AUTH_USER_MODEL)),
                ('syndic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syndic_pour', to=settings.AUTH_USER_MODEL)),
                ('syndic_adj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syndic_adj_pour', to=settings.AUTH_USER_MODEL)),
                ('tresorier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tresorier_pour', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('cotisation_mensuelle_lot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immeubles', to='copropriete.copropriete')),
            ],
            options={
                'unique_together': {('numero', 'copropriete')},
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('titre_propriete', models.FileField(blank=True, null=True, upload_to='titres_propriete/')),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='copropriete.immeuble')),
                ('proprietaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('numero', 'immeuble')},
            },
        ),
        migrations.AddConstraint(
            model_name='copropriete',
            constraint=models.UniqueConstraint(fields=('nom', 'ville'), name='unique_nom_ville'),
        ),
    ]
