# Generated by Django 3.2.25 on 2025-03-16 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copropriete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to=settings.AUTH_USER_MODEL),
        ),
    ]
