# Generated by Django 3.2.25 on 2025-03-29 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copropriete', '0002_alter_lot_proprietaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='titre_propriete',
        ),
        migrations.AddField(
            model_name='lot',
            name='titre_foncier',
            field=models.FileField(blank=True, null=True, upload_to='titres_propriete/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
