# Generated by Django 3.2.25 on 2025-03-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copropriete', '0003_auto_20250329_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='copropriete',
            name='bloquer_ajout',
            field=models.BooleanField(default=False),
        ),
    ]
