# Generated by Django 3.2.25 on 2025-03-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copropriete', '0002_alter_lot_proprietaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureClt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_facture', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copropriete.lot')),
            ],
        ),
    ]
