# Generated by Django 3.2.25 on 2025-03-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factureclt',
            old_name='is_locked',
            new_name='est_lettree',
        ),
        migrations.RenameField(
            model_name='factureclt',
            old_name='montant_total',
            new_name='montant_initial',
        ),
        migrations.AddField(
            model_name='factureclt',
            name='reste_a_lettrer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
