# Generated by Django 3.2.25 on 2025-03-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0002_auto_20250318_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureclt',
            name='reste_a_lettrer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
