# Generated by Django 3.2.25 on 2025-03-19 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copropriete', '0002_alter_lot_proprietaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotisations', '0004_lettrage_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('lot', 'Lot'), ('proprietaire', 'Propriétaire')], default='lot', max_length=15),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='copropriete.lot'),
        ),
    ]
