# Generated by Django 3.2.25 on 2025-04-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0005_auto_20250319_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureclt',
            name='est_validee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiement',
            name='est_validee',
            field=models.BooleanField(default=False),
        ),
    ]
